# Generated by Django 6.0.2 on 2026-02-15 21:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSessionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('refresh_token_hash', models.CharField(max_length=255)),
                ('exprires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.CharField(default='', max_length=500)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
            ],
            options={
                'db_table': 'auth_sessions',
            },
        ),
    ]
