# Generated by Django 6.0.2 on 2026-02-16 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authsessionmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authsessionmodel',
            old_name='exprires_at',
            new_name='expires_at',
        ),
    ]
