# Generated by Django 6.0.2 on 2026-02-19 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_exprires_at_authsessionmodel_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('code_hash', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'email_verifications',
            },
        ),
    ]
