# Generated by Django 6.0.2 on 2026-02-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailverificationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='theme_preference',
            field=models.CharField(default='light', max_length=10),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
