# Generated by Django 6.0.2 on 2026-02-21 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('title', models.CharField(max_length=100)),
                ('stake_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=8)),
                ('profit_expected', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status_id', models.UUIDField()),
                ('sport_id', models.UUIDField(blank=True, null=True)),
                ('category_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('placed_at', models.DateTimeField()),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'bets',
                'ordering': ['-placed_at'],
            },
        ),
    ]
