# Generated by Django 6.0.2 on 2026-03-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_betmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='betmodel',
            name='is_boosted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='betmodel',
            name='is_freebet',
            field=models.BooleanField(default=False),
        ),
    ]
